feature(#153): fix Android SDK 33 or higher permission issue
ttt246/Brain pull request #156
Opened 2023-07-07 01:38 UTC by peterluo3131

2023-07-07 15:31 UTC, posix4e approved these changes

2023-07-07 15:31 UTC, posix4e requested changes
Wait why is CI failing?>

2023-07-10 03:09 UTC, stackdev37 commented
It is failed for Android CI. Please resolve it. Thanks.

2023-07-10 10:12 UTC, peterluo3131 commented
I will handle it. Thanks.

2023-07-12 11:46 UTC, closed without merging