Feature/UI part2 191
ttt246/Brain pull request #213
Opened 2023-07-11 18:12 UTC by peterluo3131

2023-07-11 18:24 UTC, stackdev37 commented on .DS_Store
Remove this unusable file.

2023-07-11 19:05 UTC, stackdev37 requested changes
There are few things to be updated.

2023-07-12 07:56 UTC, peterluo3131 commented
I've updated it.

2023-07-12 08:02 UTC, stackdev37 commented on WatchApp/.DS_Store
remove this file.

2023-07-12 08:02 UTC, stackdev37 requested changes
Please update

2023-07-12 08:12 UTC, merged